version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # using private Docker image
     # with credentials stored in the UI
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/firefly-database:0.1 .

     # deploy the image
     #- run: docker push $DOCKER_USER/firefly-server:0.5

